# Generated by Django 5.1.7 on 2025-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='numero_moradia',
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
