# Generated by Django 5.1.7 on 2025-05-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_endereco_numero_moradia_endereco_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
