# Generated by Django 5.1.7 on 2025-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_endereco_numero_alter_endereco_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vestido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('descritivo', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('media_preco', models.CharField(max_length=12, verbose_name='Faixa de Preço')),
            ],
        ),
    ]
