# Generated by Django 5.1.7 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medidas_encomenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidas',
            options={'verbose_name': 'Medida', 'verbose_name_plural': 'Medidas'},
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='emissao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de emissão'),
        ),
    ]
