# Generated by Django 5.1.7 on 2025-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_funcionario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='media_preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Faixa de Preço'),
        ),
    ]
