# Generated by Django 5.1.7 on 2025-06-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_vestido_media_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='manga_comprimento',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='vestido_comprimento',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço acertado'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='retirada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de retirada'),
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='vestido',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='vestido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to='core.vestido'),
        ),
    ]
