# Generated by Django 5.1.7 on 2025-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_encomenda_manga_comprimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='busto_altura',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='cintura_altura',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='costas_largura',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='ombro_comprimento',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='quadril_altura',
        ),
        migrations.AddField(
            model_name='medidas',
            name='braco_comprimento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Comprimento do braço'),
        ),
        migrations.AddField(
            model_name='medidas',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='medidas',
            name='ombro_altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Altura do ombro'),
        ),
        migrations.AddField(
            model_name='medidas',
            name='punho_circunferencia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Circunferência do punho'),
        ),
        migrations.AddField(
            model_name='medidas',
            name='titulo',
            field=models.CharField(default='Título', max_length=40, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='busto_circunferencia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Circunferência do busto'),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='cintura_circunferencia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Circunferência da cintura'),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='quadril_circunferencia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Circunferência do quadril'),
        ),
    ]
