# Generated by Django 5.2.5 on 2025-08-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_medidas_altura_remove_medidas_busto_altura_and_more'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestido',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
