# Generated by Django 5.2.5 on 2025-08-15 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestido',
            name='cor',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to='core.cor'),
        ),
        migrations.AddField(
            model_name='vestido',
            name='cores',
            field=models.ManyToManyField(blank=True, related_name='vestidos', to='core.cor'),
        ),
    ]
