# Generated by Django 5.2.5 on 2025-08-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_vestido_cor_encomenda_cor_vestido_cores'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestido',
            name='capa',
        ),
        migrations.AddField(
            model_name='vestido',
            name='capa',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='+', to='uploader.image'),
        ),
    ]
