# Generated by Django 5.2.5 on 2025-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestido',
            name='material',
        ),
        migrations.AddField(
            model_name='vestido',
            name='material',
            field=models.ManyToManyField(blank=True, related_name='vestidos', to='core.material'),
        ),
    ]
