# Generated by Django 5.2.5 on 2025-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_vestido_material_vestido_material'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='capa',
            field=models.ManyToManyField(blank=True, default=None, related_name='+', to='uploader.image'),
        ),
    ]
