# Generated by Django 5.2.5 on 2025-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='ddd',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
