# Generated by Django 5.2.5 on 2025-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_telefone_ddd_alter_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.IntegerField(unique=True, verbose_name='CPF'),
        ),
    ]
