# Generated by Django 5.2.5 on 2025-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
    ]
